config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes do
    resources :recipe_and_material_records, only: %i[index new create destroy], shallow: true
  end
  resources :materials
  devise_for :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
# frozen_string_literal: true

class Material < ApplicationRecord
  has_many :recipe_and_material_records, dependent: :destroy
  has_many :recipes, through: :recipe_and_material_records
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  has_many :recipe_and_material_records, dependent: :destroy
  has_many :materials, through: :recipe_and_material_records
  belongs_to :user
  scope :search, ->(text) { where('name LIKE ?', "%#{text}%") }
end

app/models/recipe_and_material_record.rb
# frozen_string_literal: true

class RecipeAndMaterialRecord < ApplicationRecord
  belongs_to :recipe
  belongs_to :material
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/materials_controller.rb
# frozen_string_literal: true

class MaterialsController < ApplicationController
  def index
    @materials = if params[:search]
                   Material.where('name LIKE ?', "%#{params[:search]}%")
                 else
                   Material.all
                 end
    render json: { results: @materials.map { |material| { id: material.id, text: material.name } } }.to_json
  end
end

app/controllers/recipe_and_material_records_controller.rb
# frozen_string_literal: true

class RecipeAndMaterialRecordsController < ApplicationController
  before_action :set_recipe, only: %i[new create]
  before_action :set_recipe_and_material_record, only: :destroy

  def index
    redirect_to new_recipe_recipe_and_material_record_url
  end

  def new
    @recipe_and_material_record = @recipe.recipe_and_material_records.build
  end

  def create
    @recipe_and_material_record = @recipe.recipe_and_material_records.new(recipe_and_material_record_params)
    if @recipe_and_material_record.save
      redirect_to recipe_url(@recipe.id), notice: '已加入此材料'
    else
      render :new
    end
  end

  def destroy
    @recipe_and_material_record.destroy
    redirect_to recipe_url(@recipe.id), notice: '刪除成功'
  end

  private

  def set_recipe
    @recipe = current_user.recipes.find(params[:recipe_id])
  end

  def set_recipe_and_material_record
    @recipe_and_material_record = RecipeAndMaterialRecord.includes(recipe: :user).find_by(id: params[:id],
                                                                                          user: { id: current_user.id })
  end

  def recipe_and_material_record_params
    params.require(:recipe_and_material_record).permit(:material_id, :format, :quantity)
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
    @recipes = @recipes.search(params[:search]) if params[:search]
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.includes(:materials).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :remark)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/material_helper.rb
# frozen_string_literal: true

module MaterialHelper
  def first_3_materials_options
    options_for_select(Material.all.first(3).map { |material| [material.name, material.id] })
  end
end

app/helpers/recipe_and_material_records_helper.rb
# frozen_string_literal: true

module RecipeAndMaterialRecordsHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script><!-- jQuery base library needed -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipe_and_material_records/_form.html.erb
<%= form_with(model: recipe_and_material_record, url: [recipe, recipe_and_material_record], local: true) do |form| %>
  <p>新增材料於 <%= recipe.name %></p>

  <div>
    <select style="width: 200px" id="materials_select" name="recipe_and_material_record[material_id]">
      <%# <%= first_3_materials_options %>
    </select>
  </div>

  <div class="mb-4">
    <%= form.label :quantity, '數量' %>
    <%= form.number_field :quantity, required: true %>
  </div>

  <div class="mb-4">
    <%= form.label :format, '單位' %>
    <%= form.text_field :format, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<script>
$('#materials_select').select2({
      ajax: {
        url: '<%= materials_path %>',
        dataType: 'json',
        delay: 250,
        data: function (params) {
          var query = {
            search: params.term
          }
          // Query parameters will be ?search=[term]&type=public
          return query;
        },
        processResults: function (data) {
          return data;
        },
      },
      placeholder: '搜尋材料名稱',
      closeOnSelect: true,
      allowClear: true
  });
</script>

app/views/recipe_and_material_records/new.html.erb
<%= render 'form', recipe_and_material_record: @recipe_and_material_record, recipe: @recipe %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_field :remark %>
  </div>

  <% if recipe.persisted? %>
    <%= link_to '新增材料', new_recipe_recipe_and_material_record_path(recipe.id) %>
  <% end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<%= form_tag recipes_path, method: 'get' do %>
  <%= text_field_tag :search, params[:search], placeholder: '搜尋' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.remark %></td>
        <td><%= link_to 'Show', recipe %></td>
        <% if recipe.user.id == current_user.id %>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @recipe.name %>
</p>

<p>
<strong>description:</strong>
<%= @recipe.description %>
</p>

<p>
<strong>Remark:</strong>
<%= @recipe.remark %>
</p>

<table>
  <thead>
    <tr>
      <th>材料名稱</th>
      <th>數量</th>
      <th>單位</th>
    </tr>
  </thead>

  <tbody>
    <% @recipe.recipe_and_material_records.each do |record| %>
      <tr>
        <td><%= record.material.name %></td>
        <td><%= record.quantity %></td>
        <td><%= record.format %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @recipe.user.id == current_user.id %>
  <%= link_to 'Edit', edit_recipe_path(@recipe) %>
<% end %>
|
<%= link_to 'Back', recipes_path %>